# Spring Boot configuration
spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: 241201
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: db.changelog/db.changelog-master.yaml
# Memory
cache:
  algorithm: lru
  capacity: 5